### PR TITLE
Optimize imports and remove unused stuff

### PR DESCRIPTION
**Pull request by leletec**
I know..I failed
Just ignore the changes on paper.md

### CODE REVIEW

**Comment by okitec** [comment]
I can't merge this because you still have your "Some corrections and thoughts" commit in your fork. Hence the merge conflict. Please stand by while I will rebase your stuff.

**Comment by leletec** [comment]
Yeeah, I'm sry

**Comment by okitec** [comment]
With the power of `git rebase`, I already incorporated your one commit, so all is fine. See my commit history. :smile:

**Comment by leletec** [comment]
Great 👍

**Pull request closed without merging**
